### ISSUE TITLE
Option to reuse event loop instead of creating a new one

### ISSUE THREAD

**Issue by patrick-jones** [Martiusweb/asynctest#1]
I am using [aiopg](https://github.com/aio-libs/aiopg) in a service I am testing.  I would like to set up aiopg in a fixture and then reuse the connection pool in multiple tests. However, this is not possible because asynctest creates a new event loop for each test, meaning that the test and the connection live on separate loops.  As a result, calls from the test to aiopg code never complete.

It would be nice to optionally reuse a single event loop across many tests.

**Comment by Martiusweb** [comment]
Hi, I added a feature in a separate branch, can you test it and tell me if it works for you case?

You can now specify the class attribute ``use_default_loop = True`` (see the pull request and the comments in the commit for documentation). Instead of creating a loop before each test, the default loop is used.

You can set up the loop anywhere you want, in the tests module or in the class method ``setUpClass()``.

**Comment by patrick-jones** [comment]
This worked for me -- I set up my aiopg pool in setUpClass and was able to reuse it in multiple tests.  I also double-checked that self.loop inside a test was the same as a class attribute I set up in setUpClass.

It might be worth documenting that you don't support setUpClass as a coroutine (unless I'm missing something). I just defined a coroutine elsewhere and called it using `asyncio.get_event_loop().run_until_complete(_setup())` inside of setUpClass.

**Comment by Martiusweb** [comment]
Great, I'll merge the feature then.

I don't plan to support ``setUpClass`` as a coroutine: the ``TestSuite`` object (which calls ``setUpClass`` and ``tearDownClass``) has no knowledge of a loop, since it usually only exists during a test (setUp + test + tearDown + cleanup).

Thank you for your input!
