### ISSUE TITLE
support setUpClass and tearDownClass as coroutines

### ISSUE THREAD

**Issue by thehesiod** [Martiusweb/asynctest#26]
per https://docs.python.org/2/library/unittest.html#unittest.TestCase.setUpClass

this happens during TestSuite.run which calls self._handleClassSetUp...which means that _init_loop would need to be called much earlier.

**Comment by Martiusweb** [comment]
Hi,

This is not really possible: asynctest is designed so a loop is created and closed for each test case. It's done this way to maximize isolation between tests, hence encourage you to use setUp() instead of setUpClass().

If you don't want this behavior, you can set `TestCase.use_default_loop` to `True` (as a class attribute), it will use the loop returned by `get_event_loop()` instead of creating a new loop for each case. This way, you can set the event loop or event loop policy in setUpClass, then explicitly run your setup coroutine there.

If you think you've got a case where you really need the loop in setUpClass that should be handled by asynctest, please elaborate here.

**Comment by thehesiod** [comment]
In my case I want to create a database for a particular test class via aiopg.  I don't want to do it via setUp because it would cause the test run to take too long.  Also I want to do it during setUpClass so that I can use tearDownClass to tear it down.  I don't necessarily think the loop needs to be the same from setUpClass and setUp.  Right now as a work-around I'm doing a loop.run_until_complete in setUpClass.  I can see an issue with creating async class variables during setUpClass however that's not a hard requirement for me.

This scenario may be worth considering, if it's against your design principles I think it would at least be worth a mention as I originally thought it was going to work.  Thanks!

**Comment by thehesiod** [comment]
btw, another neat thing would be allowing side_effect to be coroutines as well.  Right now it doesn't "execute" (since calling it just returns a future) leaving you scratching your head until you realize what happened.

**Comment by Martiusweb** [comment]
I understand and I'll add a note in the doc. The thing is that if I permit setUpClass to be a coroutine, I'm afraid that it will lead to more confusion (such as tasks started in setUpClass which are expected to run during tests but won't etc).

In fact, there is also a technical downside to it: since unittest.TestSuite is not (yet?) subclassed by asynctest, it allows to add asynctest.TestCase classes in a test package without updating the whole tests toolchain (=the test runner command, such as python -m unittest).

I leave the issue open until I fix the docs.

**Comment by isaacgr** [comment]
Is there any recommended workaround for this?
