### ISSUE TITLE
missing get_child_watcher and set_child_watcher in asynctest.case._Policy

### ISSUE THREAD

**Issue by ealfie** [Martiusweb/asynctest#9]
I had a few tests using create_subproces_shell using asynctest 0.6 which ran ok.

When I upgraded to asynctest 0.7 those tests are now failing because the loop has no child watcher. This I believe is because the event loop policy has no `get_child_watcher` nor `set_child_watcher` methods.

In the test below, `SomeAsynctestTestCase` fails while `SomeUnittestTestCase` succeeds, while trying to call `get_child_watcher()`. I paste the output also.

```
import asyncio
import unittest
import asynctest

@asynctest.ignore_loop
class SomeAsynctestTestCase(asynctest.TestCase):
    def test_get_child_watcher(self):
        pol = asyncio.get_event_loop_policy()
        pol.get_child_watcher()

class SomeUnittestTestCase(unittest.TestCase):
    def test_get_child_watcher(self):
        pol = asyncio.get_event_loop_policy()
        pol.get_child_watcher()


if __name__ == "__main__":
    unittest.main()
```

```
test_get_child_watcher (__main__.SomeAsynctestTestCase) ... ERROR
test_get_child_watcher (__main__.SomeUnittestTestCase) ... ok

======================================================================
ERROR: test_get_child_watcher (__main__.SomeAsynctestTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ezequiel/pyenvs/t5/lib/python3.4/site-packages/asynctest/case.py", line 221, in run
    self._run_test_method(testMethod)
  File "/home/ezequiel/pyenvs/t5/lib/python3.4/site-packages/asynctest/case.py", line 271, in _run_test_method
    result = method()
  File "./xtest.py", line 9, in test_get_child_watcher
    pol.get_child_watcher()
  File "/home/ezequiel/opt/Python-3.4.3/lib/python3.4/asyncio/events.py", line 482, in get_child_watcher
    raise NotImplementedError
NotImplementedError

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=1)
```

**Comment by Martiusweb** [comment]
Hi, thanks for the report, 

Indeed those two methods are missing. It also seems that `asyncio.AbstractEventLoopPolicy` isn't an abstract base class (`abc`) and doesn't provide a default implementation of get_child_watcher() and set_child_watcher(), which I will report in asyncio. 

Forwarding the calls to the original policy is not sufficient as the child watcher is "attached" to a loop when created by the policy. Hence, since we create a new loop for each test, it is likely that the child watcher will not be attached to the right loop (I still have to check this, but it seems likely).

**A temporary workaround** could be to reset the child watcher policy at the begining of the test (before creating the new process), with `asyncio.set_child_watcher(None)`.

When crafting the patch I've got to ensure `{get/set}_child_watcher()` are consistent with the environment (I exists only on unix environment), I'll probably replace the child watcher during the test, and reset it to the original one (if it existed), as I do with the loop.

**Comment by Martiusweb** [comment]
Fixed with the pull request, I'll push asynctest v0.7.1.
