### ISSUE TITLE
[BUG] When CoroutineMock object raised an Exception...

### ISSUE THREAD

**Issue by yeahren** [Martiusweb/asynctest#90]
[ python 3.6 + asynctest 0.12.0 ]

```python
import asynctest

class MyException(BaseException):
     pass

class MyTestCase(asynctest.TestCase):
    @staticmethod
    async def test_await():
        mock = asynctest.CoroutineMock()
        mock.side_effect = MyException

        mock.assert_not_called()
        mock.assert_not_awaited()

        try:
            await mock()
        except MyException:
            pass

        mock.assert_called_once()
        mock.assert_awaited_once()  # FAILED,  AssertionError: Expected 'mock' to have been awaited once. Awaited 0 times.
```

as you've been able to notice the "FAILED".

**Comment by Kentzo** [comment]
Good catch!

This happens because an exception thrown by [_mock_call](https://github.com/Martiusweb/asynctest/blob/v0.12.0/asynctest/mock.py#L542) is handled by [creating](https://github.com/Martiusweb/asynctest/blob/v0.12.0/asynctest/mock.py#L566) a fake "raising" coroutine instead of a proxy that would count the await.

**Comment by Kentzo** [comment]
@yeahren The PR I just opened should fix the issue.
